### ISSUE TITLE
Add Benchmarks for parsing

### ISSUE THREAD

**Issue by Lol3rrr** [Lol3rrr/s3db#11]
Currently there is no real sense of performance apart from running the `bench.sh` script. However this is a very broad benchmark and works great to get an idea of overall real world performance, but does not lend itself to use for improving specific parts of the database.
Therefore we should add benchmarks, probably using [criterion.rs](https://crates.io/crates/criterion) or maybe consider [divan](https://crates.io/crates/divan), to both the SQL and the RA parsers.

# Tasks
- [ ] Compare possible benchmarking suits
  - [ ] [criterion.rs](https://crates.io/crates/criterion)
  - [ ] [divan](https://crates.io/crates/divan)
  - [ ] [iai-callgrind](https://crates.io/crates/iai-callgrind) for running in CI
- [ ] Add SQL Parser benchmark
- [ ] Add RA Parser benchmark
