### ISSUE TITLE
Proper Sequence support

### ISSUE THREAD

**Issue by Lol3rrr** [Lol3rrr/s3db#27]
Currently when using sequences, most likely by creating a table with a SERIAL attribute, the DB stores the type as SERIAL (which is strictly speaking not correct) and then whenever a new value for that attribute is needed, it scans the entire relation and just returns the max + 1.

This is both slow and not really correct, as different transactions might get the same new value for the sequence and we cannot actually implement any of the sequence manipulation functions.

# TODOs
- [ ] Interface for storage backends to handle sequences
- [ ] Use as Serial Types (#28)
  - [x] Implement the usage of sequences
  - [x] Attributes on Relations should reference a sequence by a unique Name, which can be stored as a TypeModifier (e.g `TypeModifier::Sequence('some-name')`)
- [ ] Standalone support
  - [ ] `CREATE SEQUENCE` query parsing
  - [ ] Query execution
  - [ ] Supporting all functions for interacting with them
